name: bog_island
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  styled_widget: 0.4.0+3
  flutter_screenutil: 5.3.1
  flutter_svg: 1.0.3
  waterfall_flow: 3.0.2
  simple_rich_text: 2.0.49
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

