name: bog_island
version: 0.0.4+4
publish_to: none
description: A Flutter project for BOG.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  styled_widget: 0.4.0+3
  flutter_screenutil: 5.3.1
  flutter_svg: 1.0.3
  waterfall_flow: 3.0.2
  url_launcher: 6.0.20
  extended_image: 6.0.2+1
  lottie: 1.2.2
  get_storage: 2.0.3
  image_gallery_saver: 1.7.1
  permission_handler: 9.2.0
  path_provider: 2.0.9
  image_picker: 0.8.4+11
  logger: 1.1.0
  resonance: 1.0.2
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_html: 
    path: ./lib/app/common/pub_custom/flutter_html-3.0.0-alpha.2/

dev_dependencies: 
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icon/Icon.jpg
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/icons/
    - assets/lotties/
  uses-material-design: true

